version: '3.9'

services:
  nuxtapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Nuxtアプリケーションのデフォルトポート
      - "9229:9229" # デバッグ用ポート
    volumes:
      - .:/usr/src/app # ローカルディレクトリをコンテナ内にマウント
      - /usr/src/app/node_modules # node_modulesはコンテナ内で管理
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true" # ファイル変更を監視するため
    command: ["npm", "run", "dev"] # 開発サーバーを起動
