version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev --inspect